/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package GUI;


import Clases.Cliente;

import Clases.Empleado;
import Clases.Factura;
import Clases.Inventario;


import Util.AdminArchivos;
import Util.AdminSerializacion;

import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20241900037 Bayron Alejandro Torres Valladares y Angel Zavala 20201900397
 */
public class frmFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmFactura private Double cantidadProducto = 0.0;
     */
    private Cliente _cliente;
    private Empleado _empleado;

    private Inventario _inventario;


    private Date fecha = new Date();
    private SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private String fechaActual = formato.format(fecha);

    private int _indiceSeleccionado = -1;
    private boolean _agregando;

    public frmFactura() {
        initComponents();
        this.setTitle("Gestión Factura");
        this.lblFecha.setText(fechaActual);
        try {
            actualizarElementosTabla();
        } catch (Exception e) {
            System.out.println("Error al actualizar los elementos " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFacturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblInfoCliente = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        lblInfoEmpleado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblInfoTotal = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTipPago = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnInicio = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Cliente:");

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSalir.setText("Salir del Sistema");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jtFacturas.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jtFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtFacturasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtFacturas);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Código:");

        lblInfoCliente.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblInfoCliente.setText("N/D");

        btnReporte.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        lblInfoEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblInfoEmpleado.setText("N/D");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Vendedor:");

        lblSV.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblSV.setText("N/D");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("Impuesto S/Ventas:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setText("Total:");

        lblInfoTotal.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblInfoTotal.setText("Monto Total");

        lblFecha.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblFecha.setText("Fecha actual");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel10.setText("FACTURA");

        lblCodigo.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblCodigo.setText("N/D");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel11.setText("FERETERIA UNAH COMAYAGUA");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel12.setText("TEL 2772-4444");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Tipo de Pago:");

        lblTipPago.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTipPago.setText("N/D");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Subtotal:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setText("Descuento:");

        lblSubtotal.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblSubtotal.setText("N/D");

        lblDescuento.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblDescuento.setText("0");

        btnInicio.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubtotal)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1))))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSV))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblInfoEmpleado)))
                        .addGap(0, 406, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCodigo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblInfoCliente))
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTipPago))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(8, 8, 8)
                                        .addComponent(lblDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addGap(53, 53, 53)
                                .addComponent(btnReporte)
                                .addGap(180, 180, 180))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(193, 193, 193))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoTotal)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(247, 247, 247))))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodigo))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTipPago))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoCliente)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblInfoEmpleado))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDescuento))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblSubtotal))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSV))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblInfoTotal))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicio)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // funcion para salirse
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jtFacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFacturasMousePressed

    }//GEN-LAST:event_jtFacturasMousePressed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        
        AdminArchivos adminA = new AdminArchivos();
        adminA.setNombreArchivo("Reporte Factura.txt");
        adminA.setContenido(MDIPrincipal.gFactura.getInfoReporte());
        adminA.escribir();

        JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
        
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        int x = (this.getDesktopPane().getWidth() - MDIPrincipal.frmVenta.getWidth()) / 2;
        int y = (this.getDesktopPane().getHeight() - MDIPrincipal.frmVenta.getHeight()) / 2;
        MDIPrincipal.frmVenta.setLocation(x, y);
        
        // TODO add your handling code here:
        this.getDesktopPane().remove(MDIPrincipal.frmVenta); 
        this.getDesktopPane().add(MDIPrincipal.frmVenta);
        MDIPrincipal.frmVenta.setVisible(true);
        MDIPrincipal.frmVenta.actualizarElementosTabla();
        this.dispose(); //cierra la ventana actual
    }//GEN-LAST:event_btnInicioActionPerformed

    /*Este metodo muestra los elemento en pantalla
    segun el objeto enviado*/
    public void mostrarElemento(Factura _factura) {
        //Establece el estado, habilitado o no

        this.lblCodigo.setText(Integer.toString(_factura.getCodigoFactura()));
        this.lblFecha.setText(formato.format(_factura.getFecha()));
        this.lblTipPago.setText("N/D");
        this.lblInfoCliente.setText(_factura.getCliente().getNombre());
        this.lblInfoEmpleado.setText(_factura.getEmpleado().getNombre());
        
        this.lblDescuento.setText(Double.toString(Math.round(_factura.getDescuento()*100.0)/100.0)+"%");
        this.lblSubtotal.setText("$"+ Double.toString(Math.round(_factura.getSubtotal()*100.0)/100.0));
        this.lblSV.setText(Double.toString(Math.round(_factura.getImpuesto()*100.0)/100.0));
       
        this.lblInfoTotal.setText("$"+Double.toString(Math.round(_factura.getMontoTotal()*100.0)/100.0));

    }

    public void actualizarElementosTabla() {

        String[] titulo = {"Producto", "Cantidad", "Precio Unidad", "Monto"};
        DefaultTableModel dt = new DefaultTableModel(MDIPrincipal.gCarrito.getArrayGestionFactura(), titulo);
        this.jtFacturas.setModel(dt);
    }

    public void estadoControles(boolean _estado) {
        //this.txtCodigo.setEditable(_estado);
        //this.txtCantidadBoleto.setEditable(_estado);
        //this.txtCantidadProducto.setEditable(_estado);
    }

    public void estadoBotones(boolean _estado) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtFacturas;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblInfoCliente;
    private javax.swing.JLabel lblInfoEmpleado;
    private javax.swing.JLabel lblInfoTotal;
    private javax.swing.JLabel lblSV;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTipPago;
    // End of variables declaration//GEN-END:variables
}
