/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Arboles.ArbolBinario;
import Clases.Inventario;
import Clases.Proveedor;
import Util.AdminArchivos;
import Util.AdminSerializacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20241900037 Bayron Alejandro Torres Valladares
 */
public class frmInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmInventario
     */
    private Proveedor _proveedor;

    private int _indiceSeleccionado = -1;
    private boolean _agregando;

    public frmInventario() {
        initComponents();
        this.setTitle("Gestión Inventario");
        try {
            actualizarElementosTabla();
        } catch (Exception e) {
            System.out.println("Error al actualizar los elementos " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblInfoProveedor1 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventarios = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        lblInfoProveedor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Stock:");

        btnGuardar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtStock.setEditable(false);
        txtStock.setBackground(new java.awt.Color(255, 255, 255));
        txtStock.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Producto:");

        btnReporte.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblInfoProveedor1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblInfoProveedor1.setText("Codigo proveedor:");

        txtProducto.setEditable(false);
        txtProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtProducto.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel8.setText("Nota: Si modificas vuelva a ingresar el código");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Precio:");

        btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Código:");

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnBuscarProveedor.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnBuscarProveedor.setText("Buscar Proveedor");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        jtInventarios.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jtInventarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtInventariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtInventarios);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblInfoProveedor.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        lblInfoProveedor.setText("Nombre proveedor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnBuscarProveedor)
                .addGap(20, 20, 20)
                .addComponent(lblInfoProveedor)
                .addGap(87, 87, 87)
                .addComponent(lblInfoProveedor1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(18, 18, 18)
                .addComponent(btnReporte))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarProveedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfoProveedor)
                            .addComponent(lblInfoProveedor1)
                            .addComponent(jLabel8))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar)
                    .addComponent(btnSalir)
                    .addComponent(btnReporte))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // los pasos 1, 2, 3 y 5 son comunes
        //Paso 1
        String codigo;
        String producto;
        String precio;
        String stock;

        codigo = this.txtCodigo.getText();
        producto = this.txtProducto.getText();
        precio = this.txtPrecio.getText();
        stock = this.txtStock.getText();

        //PAso 2
        Inventario inventario = new Inventario();

        try {

            //Paso 3
            inventario.setCodigoInventario(Integer.parseInt(codigo));
            inventario.setNombreProducto(producto);
            inventario.setPrecio(Double.parseDouble(precio));
            inventario.setStock(Integer.parseInt(stock));
            inventario.setProveedor(_proveedor);

            if (this._agregando) {
                //Nueva funcion
                /*solicitar valores a usuario
                crear instancia
                setear los valores a la instancia
                agregar instancia
                mostrar valores
                */

                //paso 4
                MDIPrincipal.gInventario.agregarInventario(inventario);
                AdminSerializacion.serializacion(MDIPrincipal.arbolInventario, "gInventarioArbol.obj");

            } else {//Editando Funcion
                /*solicitar valores a usuario
                crear instancia modificada
                setear los valores a la instancia modificada
                modificar la instancia
                mostrar valores modificados
                */

                //Paso 4

                MDIPrincipal.gInventario.modificarInventario(inventario, this._indiceSeleccionado); //ENTRAR A LA FUNCION Y INGENNAIRSELA PARA METER EL ARBOL AHI Y MODIFICAAR
                AdminSerializacion.serializacion(MDIPrincipal.arbolInventario, "gInventarioArbol.obj");
            }

            //paso 5
            actualizarElementosTabla();
            estadoControles(false);
            estadoBotones(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Favor ingresar correctamente el codigo");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + e.getMessage());
        }

        //paso 6: serializar informacion
        AdminSerializacion.serializacion(MDIPrincipal.gInventario, "gInventario.obj");
        //AdminSerializacion.serializacion(MDIPrincipal.arbolInventario, "gInventarioArbol.obj");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        AdminArchivos adminA = new AdminArchivos();
        adminA.setNombreArchivo("Reporte Inventario.txt");
        adminA.setContenido(MDIPrincipal.gInventario.getInfoReporte());
        adminA.escribir();

        JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Metodo para eliminar el objeto guardado
        if (_indiceSeleccionado >= 0) {
            int resultado = JOptionPane.showConfirmDialog(null, "Estas seguro?", "Warning", JOptionPane.YES_NO_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                //elimina registro de LkL
                MDIPrincipal.gInventario.eliminarInventario(_indiceSeleccionado);
                //actualizarElementosTabla();
                //paso 6: serializar informacion
                AdminSerializacion.serializacion(MDIPrincipal.gInventario, "gInventario.obj");

                //Se deja nula la instancia
                MDIPrincipal.arbolInventario=null;
                MDIPrincipal.arbolInventario= new ArbolBinario();
                //borra el arbol
                AdminSerializacion.eliminarArchivoSerializado("gInventarioArbol.obj");

                //lo vuelve a rellenar sin el dato que se borro
                for (int i = 0; i < MDIPrincipal.gInventario.getInventarios().size(); i++) {
                    MDIPrincipal.gInventario.agregarInventario(MDIPrincipal.gInventario.getInventarios().get(i));
                }
                //serializa el nuevo arbol
                AdminSerializacion.serializacion(MDIPrincipal.arbolInventario, "gInventarioArbol.obj");
                MDIPrincipal.arbolInventario.mostrarInOrden(MDIPrincipal.arbolInventario.getRaiz());

                //actualiza la tabla en la interfaz
                actualizarElementosTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor seleccione un elemento de la tabla que desea eliminar.");
        }
        estadoControles(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this._agregando = true;
        estadoControles(true);
        estadoBotones(false);

        this.txtCodigo.setText("");
        this.txtProducto.setText("");
        this.txtPrecio.setText("");
        this.txtStock.setText("");
        this.lblInfoProveedor.setText("Nombre Proveedor");
        this.lblInfoProveedor1.setText("Codigo Proveedor");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        // TODO add your handling code here:
        String _codigoInventario = JOptionPane.showInputDialog("Ingrese el codigo del Inventario");

        Inventario _inventarioEncontrado = MDIPrincipal.gInventario.buscar(Integer.parseInt(_codigoInventario));
        if (_inventarioEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Inventario no encontrada");
        } else {
            mostrarElemento(_inventarioEncontrado);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        this._agregando = false;
        estadoControles(true);
        estadoBotones(false);

        this.txtCodigo.setEditable(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // funcion para salirse
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        String _codigoProveedor;
        _codigoProveedor = JOptionPane.showInputDialog(this, "Ingrese el codigo del Proveedor");

        _proveedor = MDIPrincipal.gProveedor.buscar(Integer.parseInt(_codigoProveedor));

        if (_proveedor == null) {
            JOptionPane.showMessageDialog(this, "Proveedor no encontrada " + _codigoProveedor);
        } else {
            this.lblInfoProveedor.setText("Nombre: " + _proveedor.getEmpresa());
            this.lblInfoProveedor1.setText("Codigo: " + _proveedor.getCodigoProveedor());
        }
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void jtInventariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInventariosMousePressed
        _indiceSeleccionado = this.jtInventarios.getSelectedRow();
        if (_indiceSeleccionado != -1) {
            Inventario _inventario = MDIPrincipal.gInventario.getInventarioByIndex(_indiceSeleccionado);
            mostrarElemento(_inventario);

        }
    }//GEN-LAST:event_jtInventariosMousePressed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    /*Este metodo muestra los elemento en pantalla
    segun el objeto enviado*/
    public void mostrarElemento(Inventario _inventario) {
        //Establece el estado, habilitado o no

        this.txtCodigo.setText(Integer.toString(_inventario.getCodigoInventario()));
        this.txtProducto.setText(_inventario.getNombreProducto());
        this.txtPrecio.setText(Double.toString(_inventario.getPrecio()));
        this.txtStock.setText(Integer.toString(_inventario.getStock()));
        this.lblInfoProveedor.setText(_inventario.getProveedor().getEmpresa());
        this.lblInfoProveedor1.setText(Integer.toString(_inventario.getProveedor().getCodigoProveedor()));
    }

    public void actualizarElementosTabla() {

        String[] titulo = {"Código", "Producto", "Precio", "Stock", "Proveedor"};

        DefaultTableModel dt = new DefaultTableModel(MDIPrincipal.gInventario.getArrayGestion(), titulo);
        this.jtInventarios.setModel(dt);
    }

    public void estadoControles(boolean _estado) {
        this.txtCodigo.setEditable(_estado);
        this.txtProducto.setEditable(_estado);
        this.txtPrecio.setEditable(_estado);
        this.txtStock.setEditable(_estado);
    }

    public void estadoBotones(boolean _estado) {
        this.btnBuscar.setEnabled(_estado);
        this.btnModificar.setEnabled(_estado);
        this.btnEliminar.setEnabled(_estado);
        this.btnGuardar.setEnabled(!_estado);
        this.btnNuevo.setEnabled(_estado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtInventarios;
    private javax.swing.JLabel lblInfoProveedor;
    private javax.swing.JLabel lblInfoProveedor1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

}
