/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Clases.CarritoCompras;
import Clases.Cliente;
import Clases.Venta;
import Clases.Inventario;
import Gestiones.GestionCarritoCompras;
import Util.AdminArchivos;
import Util.AdminSerializacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20241900037 Bayron Alejandro Torres Valladares y Angel Zavala 20201900397
 */
public class frmVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVenta
     */
    private Cliente _cliente;
    private Inventario _inventario;

    private int _indiceSeleccionado = -1;
    private boolean _agregando;

    public frmVenta() {
        initComponents();
        this.setTitle("Gestión Venta");
        try {
            if(!MDIPrincipal.gLBI.isEmpty()){
                DefaultTableModel model = (DefaultTableModel) this.jtVentas.getModel();
                model.setRowCount(0);
                MDIPrincipal.gLBI.clear(); 
                AdminSerializacion.serializacion(MDIPrincipal.gLBI, "gInventarioLB.obj");


            }
            actualizarElementosTabla();
        } catch (Exception e) {
            System.out.println("Error al actualizar los elementos " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVentas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        btnBuscarSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("BUSCAR PRODUCTOS ");

        btnCarrito.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCarrito.setText("IR AL CARRITO DE COMPRAS");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnBuscarProducto.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jtVentas.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jtVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtVentasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtVentas);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("FERRTERIA UNAH COMAYAGUA");

        txtProducto.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        txtProducto.setText("Ingrese el Producto: TUBO, CLAVO, etc... en mayusculas");
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        btnBuscarSalir.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnBuscarSalir.setText("SALIR");
        btnBuscarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarProducto)
                                    .addGap(24, 24, 24))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(btnBuscarSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
        if (!MDIPrincipal.gLBI.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) this.jtVentas.getModel();
            model.setRowCount(0);
            MDIPrincipal.gLBI.clear();
            AdminSerializacion.serializacion(MDIPrincipal.gLBI, "gInventarioLB.obj");
        }

        this.getDesktopPane().remove(MDIPrincipal._frmCarrito);
        this.getDesktopPane().add(MDIPrincipal._frmCarrito);

        // Para centrar el formulario
        int x = (this.getDesktopPane().getWidth() - MDIPrincipal._frmCarrito.getWidth()) / 2;
        int y = (this.getDesktopPane().getHeight() - MDIPrincipal._frmCarrito.getHeight()) / 2;
        MDIPrincipal._frmCarrito.setLocation(x, y);

        // Mostrar y actualizar
        MDIPrincipal._frmCarrito.setVisible(true);
        MDIPrincipal._frmCarrito.actualizarElementosTabla();
        this.dispose();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        MDIPrincipal.arbolInventario.mostrarInOrden(MDIPrincipal.arbolInventario.getRaiz());
        //verifica si la lista de producto buscados no esta vacia para borrar el cache
        if(!MDIPrincipal.gLBI.isEmpty()){
            DefaultTableModel model = (DefaultTableModel) this.jtVentas.getModel();
            model.setRowCount(0);
            MDIPrincipal.gLBI.clear();
            AdminSerializacion.serializacion(MDIPrincipal.gLBI, "gInventarioLB.obj");

        }

        //hace el filtro
        String producto;
        producto=this.txtProducto.getText();
        MDIPrincipal.gInventario.buscarInventarioPorNombre(producto,this.txtProducto.getText());
        //serializa el filtro
        AdminSerializacion.serializacion(MDIPrincipal.gLBI, "gInventarioLB.obj");
        this.actualizarElementosTabla();
        //AdminSerializacion.serializacion(MDIPrincipal.arbolInventario, "gInventarioArbol.obj");
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void jtVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVentasMousePressed
        this._indiceSeleccionado = this.jtVentas.getSelectedRow();
        if (_indiceSeleccionado != -1) {
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea Agregar el producto al Carrito?", "Warning", JOptionPane.YES_NO_OPTION);
            if(resultado==JOptionPane.YES_NO_OPTION){
                Inventario _producto = MDIPrincipal.gLBI.get(this._indiceSeleccionado);
                CarritoCompras auxCarrito=new CarritoCompras();
                auxCarrito.setProducto(_producto);
                MDIPrincipal.gCarrito.agregar(auxCarrito);
                AdminSerializacion.serializacion(MDIPrincipal.gCarrito,"gCarrito.obj");
                JOptionPane.showMessageDialog(this,_producto.getNombreProducto() +" Agregado al Carrito");
            }
            //mostrarElemento(_venta);

        }
    }//GEN-LAST:event_jtVentasMousePressed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void btnBuscarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSalirActionPerformed
        // TODO add your handling code here:
        //Borrado del carrito
        MDIPrincipal.gCarrito.getCarritoComp().clear();
        AdminSerializacion.serializacion(MDIPrincipal.gCarrito, "gCarrito.obj");

        // funcion para salirse
        this.dispose();
    }//GEN-LAST:event_btnBuscarSalirActionPerformed

    public void actualizarElementosTabla() {

        String[] titulo = {"Producto", "Precio"};
        
        DefaultTableModel dt = new DefaultTableModel(MDIPrincipal.gInventario.getArrayGestionFiltro(), titulo);
        this.jtVentas.setModel(dt);
    }
    /*Este metodo muestra los elemento en pantalla
    segun el objeto enviado*/
    public void mostrarElemento(Venta _venta) {
        //Establece el estado, habilitado o no

        this.txtProducto.setText(Integer.toString(_venta.getCodigoVenta()));
        //this.lblInfoCliente.setText(_venta.getCliente().getNombre());
        //this.lblInfoProducto.setText(_venta.getInventario().getNombreProducto());

    }



    public void estadoControles(boolean _estado) {
        //this.txtProducto.setEditable(_estado);
    }

    public void estadoBotones(boolean _estado) {
        //this.btnBuscar.setEnabled(_estado);
        //this.btnModificar.setEnabled(_estado);
        //this.btnEliminar.setEnabled(_estado);
        //this.btnGuardar.setEnabled(!_estado);
        //this.btnNuevo.setEnabled(_estado);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarSalir;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtVentas;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables

}
